### ISSUE TITLE
music id3 short text detect

### ISSUE THREAD

**Issue by goog** [BYVoid/uchardet#14]
for music id3 short text detection, charset seems often return ""

**Comment by BYVoid** [comment]
This is expected, because it's really not possible to detect the charset of a short byte-stream using a statistical algorithm.

**Comment by goog** [comment]
have to dig the encoding number, or is there a better way to make it?

**Comment by BYVoid** [comment]
Can you try to concatenate multiple short texts together?

**Comment by goog** [comment]
what's the threshold length to apply the library? is there a reference value

**Comment by BYVoid** [comment]
No. The longer the more likely to be detected.

**Comment by goog** [comment]
thx!
