### ISSUE TITLE
Can't detect GBK.

### ISSUE THREAD

**Issue by Coolerfall** [BYVoid/uchardet#31]
[gbk.txt](https://github.com/BYVoid/uchardet/files/195154/gbk.txt)
The detected result is UTF-8, but it's GBK actually.

**Comment by Jehan** [comment]
It detects ISO-8859-7 on the master version, but anyway that's still wrong. I think that's probably the same as issue 23. Basically that's a GBK file which does not use escape sequence and our detection algorithm is limited there.
I'd welcome any patch for this.

**Comment by Jehan** [comment]
Moving bug reports to the new project hosting.
Work will happen there: https://bugs.freedesktop.org/show_bug.cgi?id=97521
