### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Coacher** [BYVoid/uchardet#32]
Hello.

Are there any plans regarding the next uchardet release?

**Comment by Jehan** [comment]
I am moving our code to GNOME infrastructure and was hoping to make the release then. But the bugtracker is stalling a bit (the code is already synced on GNOME git).
I guess I can do a release before.
But probably not immediately since I am a bit busy but probably mid-May.

**Comment by Coacher** [comment]
I see. Thank you for the info.

**Comment by Jehan** [comment]
New release done 0.0.6 done on freedesktop hosting.
See https://www.freedesktop.org/wiki/Software/uchardet/
Tarballs available from: https://www.freedesktop.org/software/uchardet/releases/
Release notes: https://cgit.freedesktop.org/uchardet/uchardet/tag/?id=v0.0.6

**Comment by Coacher** [comment]
Thank you. Coming to Gentoo very soon.
