### ISSUE TITLE
Possibly incomplete project license

### ISSUE THREAD

**Issue by Coacher** [BYVoid/uchardet#34]
Hello.

README says that license is just MPL-1.1.
License headers inside C files permit any of MPL-1.1, GPL-2+, LGPL-2.1+.

Shouldn't README offer multiple licenses as well?

**Comment by Jehan** [comment]
You are right. I updated README and COPYING as well with commit 602c1ab.
Thanks!

**Comment by Coacher** [comment]
Thank you very much.
